### ISSUE TITLE
solarbank_info.backup_info" has to be type "string" but received type "object" - Logfile wird vollgeschrieben

### ISSUE THREAD

**Issue by Krys91** [ronny130286/ioBroker.ankersolix2#20]
Neuerdings wird das Logfile mit der Meldung "State value to set for "ankersolix2.0.09d20f23-d678-4a6f-9e86-d7181b9c7aa5.solarbank_info.backup_info" has to be type "string" but received type "object"" vollgeschrieben.

![image](https://github.com/user-attachments/assets/907da6e2-6ded-4717-858b-0f05964cfeec)

Installierte Version:
0.0.3-alpha.0

Plattform: linux
Betriebssystem: linux
Architektur: x64
CPUs: 4
Geschwindigkeit: 2396 MHz
Modell: Intel(R) Celeron(R) J4105 CPU @ 1.50GHz
RAM: 8 GB
System-Betriebszeit: 7 T. 18:21:24
Node.js: v20.18.0

**Comment by ronny130286** [comment]
Ich habe es gestern angepasst, Anker hat das Json erweitert. Ich habe es jedoch nur auf Github aktualisiert, da ich gerade Problem mit dem Release haben, da muss ich nochmal gucken warum das plötzlich passiert

**Comment by Krys91** [comment]
Hab von Github installiert, seitdem ist alles in Ordnung. DANKE.

**Comment by ronny130286** [comment]
after update i.O
