### ISSUE TITLE
Problem Aktualisierung der Objektdaten in ioBroker

### ISSUE THREAD

**Issue by MarkusSuttner** [ronny130286/ioBroker.ankersolix2#25]
Hello, I have the adapter Anker Solix 2 [ronny130286] running in the current version 1.0.3 on windows 11. Windows 11 and iobroker is all on the latest version, except for the VIS, which is still on version 1. With your adapter I have the problem that the values are only updated in the ioBroker when I open the Anker Solix app on the mobile phone. Otherwise, the last values will remain in permanently. The note with the error 401 was very good! You could also give a reference to a second account (via family invitation) in the Anker app so that you don't block each other with the app and ioBroker. Thank you very much! Markus

Hallo, ich haben den Adapter Anker Solix 2 [ronny130286] in der aktuellen Version 1.0.3 auf windows 11 laufen. Windows 11 und iobroker ist alles auf der aktuellsten Version, bis auf die VIS, die ist noch auf Version 1. Bei Deinem Adapter habe ich das Problem, dass die Werte nur  im ioBroker aktualisiert werden, wenn ich auf dem Handy die Anker Solix App öffne. Sonst bleiben die letzten Werte so dauerhaft drin. Der Hinweis mit dem Fehler 401 war sehr gut! Auch könnten man noch einen Hinweis auf ein zweites Konto (über Familien Einladung) in der Anker App geben, damit man sich nicht gegenseitig mit der App und ioBroker blockiert. Lieben Dank! Markus

**Comment by ronny130286** [comment]
Hallo Markus,
der Hinweis mit dem Familie Account steht im Readme unter Config (gleich im ersten Punkt).
Das mit dem Werten aktualisieren, wurde schon im Forum besprochen, Anker aktualisiert leider die Daten nicht oft genug.
Ich habe z.B. das Smartmeter und dort bekomme ich bei jedem laden, neue Werte ;)

Gruß Ronny

**Comment by MarkusSuttner** [comment]
Hallo Ronny,

sorry; tatsächlich "familie" überlesen...
Anker scheint bzgl. Software nicht so dolle zu sein-bin schon über ein paar Fehler gestolpert.
Mit Smartmeter meinst Du das von Anker oder ein Shelly.
Also ich hab mein Shelly EM schon wieder in Betrieb genommen...aber wie kommt man an aktuelle Werte von Batteriestand und aktuellem Strom ins Hausnetz? Was die Werte von Anker im Adapter betrifft, die ändern sich wirklich gar nicht; auch mit einem Neustart des Adapters nicht. Erst wenn ich die Anker App auf dem Handy öffne.
Gibt es da was Erschöpfendes und welches Forum meinst Du?
Ich finde es toll, dass Du Dich so engagierst! Habe im Github nichts mit "Donate" gefunden oder ist das nicht mehr üblich?


LG aus Chemnitz! Markus

**Comment by ronny130286** [comment]
Guck mal hier: https://forum.iobroker.net/topic/69229/anker-adapter/
Ich verwende das Anker Smartmeter und unter ankersolix2.0..grid_info.grid_to_home_power ändert sich bei mir immer was ;)

Wenn sich bei dir nichts ändern, kann es auch sein, dass deine Powerbank leer bzw. im Tiefschlaf ist, wie meine seit ca 2 Wochen :(
Den "Donate" Button gibt es bei mir nicht, ich mache das als Hobby und Eigeninteresse ;)

Ich würde den Issus erstmal zu machen => gucke mal ins Forum oder gern per Mail  ;)
