### ISSUE TITLE
Hi, thanks for your work on this adapter. Missing the values for daily PV yield. Would it be possible to add that. Would need it for PVoutput.org. Thank you.

### ISSUE THREAD

**Issue by LocutusB** [ronny130286/ioBroker.ankersolix2#26]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by BigMike71** [comment]
The day counter has no actual value. It is added up in the cloud!

I use the "ankersolix2....solarbank_info.total_photovoltaic_power" in a small blockly
Query the value every 60 seconds, add it to itself and save it as an intermediate variable, and then divide it by 60, so
You have 99.5% of the desired value in W/h :)

**Comment by LocutusB** [comment]
Thank you, will give it a try. Should be good for the daily statistics.

**Comment by ronny130286** [comment]
Hi, the next update will be incl. this fetaure, here 2 pics from the data of my test system. it will be realeased in abouut 2-3 days.

![day](https://github.com/user-attachments/assets/165a6389-c314-4419-86a6-6253d1f20022)
![week](https://github.com/user-attachments/assets/f1e82d58-1c7b-4e2c-9a44-fd0e96687532)


so you can see the actual week and the actual day
