### ISSUE TITLE
Great idea! Currently no data points available for SOLIX 2 E1600 pro

### ISSUE THREAD

**Issue by flispy** [ronny130286/ioBroker.ankersolix2#7]
Hi,

I installed it within iobroker with success. But unfortunately no data points or debug messages were shown.
If there is something to test - please do not hesitate to contact me. I am very interested in using this adapter!

<img width="967" alt="Bildschirmfoto 2024-09-23 um 12 50 35" src="https://github.com/user-attachments/assets/5c745566-e65e-492f-944f-f733fd5a9076">

<img width="1260" alt="Bildschirmfoto 2024-09-23 um 12 54 47" src="https://github.com/user-attachments/assets/8f607707-f583-4561-a378-9bab93203992">

**Comment by ronny130286** [comment]
Do you use a secoundary account(family account) or your main account from App?

**Comment by flispy** [comment]
> Do you use a secoundary account(family account) or your main account from App? Can you please post the log and set it to debug?

Hi, I am using a secondary account, but I get the same issue with primary account. Today it is an other issue - I am getting an 401 error.
`Failed fetching or publishing printer dataAxiosError: Request failed with status code 401`

It seems the adapter tries to connect and cannot authenticate. Definitely I am using the same mail address and password. Could it be there is an issue with my password because it has special characters in it?

**Comment by ronny130286** [comment]
This error code says that you credentinals are wrong. Stop the adapter and look under /opt/iobroker/iobroker-data/ankersolix2.0/ there is a session.data => delete this one and start the adapter again.

The special characters in passwort are no problem, i have it too.

**Comment by ronny130286** [comment]
please install the update and check again

**Comment by flispy** [comment]
not fixed with the update I will try to delete the session data manually <img width="1405" alt="Bildschirmfoto 2024-09-26 um 08 56 45" src="https://github.com/user-attachments/assets/a98f0105-5df5-402e-b503-3c2e1ca7f869">

**Comment by flispy** [comment]
removing the data manually from /opt/iobroker/iobroker-data/ankersolix2.0 resolved the issue.
